# Generated by Django 4.2.3 on 2023-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_img',
            field=models.ImageField(default=None, upload_to='pokemon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(to='home.ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='home.type'),
        ),
    ]
