# Generated by Django 4.2.3 on 2023-07-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ability_type_pokemon_description_pokemon_pokemon_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='flavor',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
