# Generated by Django 4.2.3 on 2023-07-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pokemon_flavor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['id']},
        ),
    ]
