# Generated by Django 4.2.3 on 2023-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_pokemon_height_alter_pokemon_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_img',
            field=models.TextField(max_length=1000),
        ),
    ]
