# Generated by Django 4.2.3 on 2023-08-01 17:58

import autoslug.fields
from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230801_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, slugify=home.models.Pokemon.generate_slug),
            preserve_default=False,
        ),
    ]
