# Generated by Django 4.2.3 on 2023-08-01 19:20

import autoslug.fields
from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230801_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=home.models.Pokemon.generate_slug),
        ),
    ]
