# Generated by Django 4.2.3 on 2023-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_evolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_chain',
            field=models.ManyToManyField(to='home.evolution'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='chain',
            field=models.CharField(max_length=100),
        ),
    ]
