# Generated by Django 4.2.3 on 2023-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_evolution_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolution_chain',
        ),
        migrations.DeleteModel(
            name='Evolution',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution_chain',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
