# Generated by Django 4.2.3 on 2023-08-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_pokemon_evolution_chain_delete_evolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolution_chain',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution_chain',
            field=models.ManyToManyField(to='home.evolution'),
        ),
    ]
