# Generated by Django 4.2.3 on 2023-08-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_evolution_remove_pokemon_evolution_chain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolution',
            options={'ordering': ['pk']},
        ),
    ]
