# Generated by Django 5.0.6 on 2024-06-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_evolution_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ability',
            table='abilities',
        ),
        migrations.AlterModelTable(
            name='evolution',
            table='evolution',
        ),
        migrations.AlterModelTable(
            name='pokemon',
            table='pokemon',
        ),
        migrations.AlterModelTable(
            name='type',
            table='types',
        ),
    ]
