# Generated by Django 5.0.6 on 2024-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_ability_table_alter_evolution_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='habitat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='is_legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='is_mythical',
            field=models.BooleanField(default=False),
        ),
    ]
