# Generated by Django 5.0.6 on 2024-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_pokemon_habitat_pokemon_is_legendary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemon_abilities', to='home.ability'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_chain',
            field=models.ManyToManyField(related_name='pokemon_evolution_chain', to='home.evolution'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon_types', to='home.type'),
        ),
    ]
