# Generated by Django 5.0.6 on 2024-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_pokemon_abilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('size', models.IntegerField()),
                ('smoothness', models.IntegerField()),
                ('soil_dryness', models.IntegerField()),
                ('image', models.CharField(max_length=1000)),
                ('growth_time', models.IntegerField()),
                ('max_harvest', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Berry',
                'verbose_name_plural': 'Berries',
                'db_table': 'berry',
                'ordering': ['id'],
            },
        ),
    ]
