# Generated by Django 5.0.6 on 2024-11-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_berry'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
